### ISSUE TITLE
The captcha was not solving 

### ISSUE THREAD

**Issue by TheScreem** [Edouard127/reddit-account-generator#1]
Found captcha, solving...
panic: api2captcha: API error

**Comment by TheScreem** [comment]
Nevermind, it's because i should buy it

**Comment by TheScreem** [comment]
where should i put my api key ?

**Comment by Edouard127** [comment]
> where should i put my api key ?

.env

**Comment by Edouard127** [comment]
API_KEY=key

**Comment by TheScreem** [comment]
Thanks i just find it
But the error seems the same

**Comment by TheScreem** [comment]
![image](https://github.com/Edouard127/reddit-account-generator/assets/37018358/9f5f4393-ebc8-482c-8924-e761cf9a39e9)
![image](https://github.com/Edouard127/reddit-account-generator/assets/37018358/8737c4c6-6f35-4bfb-b2a8-17391845eb30)

**Comment by Edouard127** [comment]
Make sure the key is good, happened to me

**Comment by TheScreem** [comment]
Yeah but it seems good

**Comment by TheScreem** [comment]
Could be that ?
![image](https://github.com/Edouard127/reddit-account-generator/assets/37018358/89340ea4-f44d-423a-865e-3e197e0256d4)

**Comment by Edouard127** [comment]
This is the reddit recaptcha info, you shouldn't touch that

**Comment by TheScreem** [comment]
Ok i understand

**Comment by TheScreem** [comment]
The error is here 
![image](https://github.com/Edouard127/reddit-account-generator/assets/37018358/bf000562-9dc3-4c2c-9503-3801527be522)

**Comment by TheScreem** [comment]
Ok i found why, it's because i forgot to rebuild the project
