### ISSUE TITLE
generating invalid username (20+ symbols)

### ISSUE THREAD

**Issue by anelfer** [Edouard127/reddit-account-generator#3]
{"username":"3c5g0y0l4l6l9v3s5h6e2i9d","password":"SECRET"}
<img width="327" alt="image" src="https://github.com/Edouard127/reddit-account-generator/assets/49652074/50db34ae-be6f-438f-b8c9-031d489375e4">

**Comment by TheScreem** [comment]
Yes i've got the same issue, you should generator less long username and password to work

**Comment by Edouard127** [comment]
Outdated issue, please use the latest commit
