### ISSUE TITLE
overwriting json

### ISSUE THREAD

**Issue by anelfer** [Edouard127/reddit-account-generator#4]
after generating 5 accounts, the last account began to be overwritten, and not to supplement the json

**Comment by TomiLikesToCode** [comment]
how did you create the .env file

**Comment by anelfer** [comment]
I didn't, I did `export API_KEY=`

**Comment by TomiLikesToCode** [comment]
like this?: redditgenerator.exe export API_KEY=asd

**Comment by TomiLikesToCode** [comment]
but where did you type export API_KEY=

**Comment by TomiLikesToCode** [comment]
nevermind it works

**Comment by TomiLikesToCode** [comment]
i have my first user :)

**Comment by Edouard127** [comment]
I think this should've been fixed in this commit ? 2832d76
I'm not sure anymore it's been a while
