### ISSUE TITLE
IT'S A VIRUS 

### ISSUE THREAD

**Issue by TomiLikesToCode** [Edouard127/reddit-account-generator#5]
THIS SOFTWARE DROPPS OFF A FILE NAMED "LEAKLESS.EXE" IN LOCAL TEMP, AND THIS FILE IS A VIRUS ALL ANTI-VIRUS SOFTWARE FLAGGS THIS FILE!!!

**Comment by anelfer** [comment]
lol) this is a file from this repository https://github.com/ysmood/leakless . It is needed to prevent memory leaks
