### ISSUE TITLE
The vérification email was not found

### ISSUE THREAD

**Issue by TheScreem** [Edouard127/reddit-account-generator#6]
When i create user often, i didin't receive the confirmation email.
To use tor you just need to open tor.exe and that it ?

**Comment by TheScreem** [comment]
Should i keep 10min between ?

**Comment by TheScreem** [comment]
I just test and the bot ip doesn't changed

**Comment by Edouard127** [comment]
> I just test and the bot ip doesn't changed

Because you didn't put a circuit changing configuration
Please check the readme
